---
detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    public_methods_only: true
  DuplicateMethodCall:
    allow_calls:
      - logger
  UncommunicativeVariableName:
    accept:
      - x
      - y

directories:
  'lib/pong/systems':
    FeatureEnvy:
      enabled: false
    UtilityFunction:
      enabled: false
  'spec/integration/ecs/systems':
    FeatureEnvy:
      enabled: false
  'lib/ecs/ext/dry/struct':
    NestedIterators:
      enabled: false
  'spec':
    UtilityFunction:
      enabled: false
