AllCops:
  Exclude:
    - 'bin/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'
