require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'id'
    - '_'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'
