require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'id'
    - 'x'
    - 'y'
    - '_'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

# RSpec

RSpec/Be:
  Enabled: false
